import test from "node:test";
import assert from "node:assert/strict";
import { PGlite } from "@electric-sql/pglite";
import { drizzle } from "drizzle-orm/pglite";
import { migrate } from "drizzle-orm/pglite/migrator";
import { readFile } from "node:fs/promises";
import { eq } from "drizzle-orm";
import * as legacy from "../../shared/schema.ts";
import * as schema from "../../shared/schema-v2.ts";
import { createLibraryService, DomainError } from "./library-service.ts";
import { createAccountService } from "./account-service.ts";
import { parseRowanArchive } from "../../shared/rowan-archive.ts";
import { effectiveProgress } from "../../shared/reading-progress.ts";
const key = () => crypto.randomUUID();
const at = (day: number) => `2026-09-${String(day).padStart(2,"0")}T12:00:00.000Z`;
const fails = (code: string) => (error: unknown) => error instanceof DomainError && error.code === code;

test("progress corrections preserve originals, recalculate history, and survive restore", async t => {
  const client = new PGlite();
  t.after(() => client.close());
  const database = drizzle(client, { schema: legacy });
  for (const file of ["0000_initial_schema.sql", "0002_book_metadata.sql"]) await client.exec(await readFile(`migrations/${file}`, "utf8"));
  await migrate(database, { migrationsFolder: "migrations-v2" });
  await migrate(database, { migrationsFolder: "migrations-v2" });
  const db = database as unknown as Parameters<typeof createLibraryService>[0];
  const library = createLibraryService(db, { fetchWork: async () => { throw new Error("offline"); } });
  const accounts = createAccountService(db);
  await database.insert(legacy.users).values([{ id: 1, username: "one" }, { id: 2, username: "two" }]);
  const actor = { userId: 1 }, other = { userId: 2 };
  const book = await library.saveManual(actor, { key: key(), title: "Correction test", author: "Reader", format: "book", total: 200 });
  const started = await library.startReading(actor, { key: key(), userBookId: book.userBookId, expectedVersion: 0, startedAt: at(1), unit: "page", position: 40 });
  const sessionId = started.sessionId!;
  await library.recordProgress(actor, { key: key(), sessionId, expectedVersion: 0, position: 65, occurredAt: at(2) });
  await library.recordProgress(actor, { key: key(), sessionId, expectedVersion: 1, position: 80, occurredAt: at(3) });
  const getHistory = () => library.readingHistory(actor, book.userBookId);
  const original = (await getHistory()).entries.find(e => e.position === 65)!;
  const request = { key: key(), sessionId, entryId: original.id, expectedVersion: 2, action: "correct" as const, position: 60, occurredAt: at(2), reason: "Mistyped the page" };

  await t.test("ownership and invalid edits leave no writes", async () => {
    await assert.rejects(library.correctProgress(other, request), fails("NOT_FOUND"));
    await assert.rejects(library.correctProgress(actor, { ...request, position: 90 }), fails("INVALID_TRANSITION"));
    await assert.rejects(library.correctProgress(actor, { ...request, occurredAt: at(4) }), fails("INVALID_TRANSITION"));
    await assert.rejects(library.correctProgress(actor, { ...request, occurredAt: "2026-08-01T00:00:00.000Z" }), fails("INVALID_TRANSITION"));
    assert.equal((await getHistory()).entries.length, 3);
    assert.equal((await getHistory()).sessions[0].version, 2);
  });
  await t.test("retry creates one retained correction and replaces the calendar observation", async () => {
    const result = await library.correctProgress(actor, request);
    assert.deepEqual(await library.correctProgress(actor, request), result);
    const history = await getHistory();
    assert.equal(history.entries.length, 4);
    assert.equal(history.entries.find(e => e.id === original.id)!.position, 65);
    assert.deepEqual(effectiveProgress(history.entries).map(e => e.position), [40,60,80]);
    assert.equal(history.sessions[0].position, 80);
    assert.equal(history.sessions[0].loggedProgress, 40);
    const calendar = await library.calendar(actor, { from: at(1), to: at(5) });
    assert.ok(!JSON.stringify(calendar).includes('"position":65'));
    assert.ok(JSON.stringify(calendar).includes('"position":60'));
    await assert.rejects(library.correctProgress(actor, { ...request, position: 61 }), fails("IDEMPOTENCY_CONFLICT"));
    await assert.rejects(library.correctProgress(actor, { ...request, key: key() }), fails("VERSION_CONFLICT"));
  });
  await t.test("removal recalculates current position; corrected dates move calendar events", async () => {
    let history = await getHistory();
    const latest = history.entries.find(e => e.position === 80)!;
    await library.correctProgress(actor, { ...request, key: key(), entryId: latest.id, expectedVersion: 3, action: "remove", reason: "Accidental duplicate log" });
    history = await getHistory();
    assert.equal(history.sessions[0].position, 60);
    assert.equal(history.sessions[0].loggedProgress, 20);
    assert.ok(history.entries.find(e => e.supersedesId === latest.id)?.voided);
    const current = effectiveProgress(history.entries).find(e => e.position === 60)!;
    await library.correctProgress(actor, { ...request, key: key(), entryId: current.id, expectedVersion: 4, occurredAt: at(3) });
    const oldDay = await library.calendar(actor, { from: at(2), to: at(3) });
    assert.ok(!JSON.stringify(oldDay).includes('"kind":"progress"'));
    await library.recordProgress(actor, { key: key(), sessionId, expectedVersion: 5, position: 90, occurredAt: at(4) });
    await library.transitionReading(actor, { key: key(), sessionId, expectedVersion: 6, action: "finish", occurredAt: at(5) });
    const terminal = await getHistory();
    const last = effectiveProgress(terminal.entries).at(-1)!;
    await assert.rejects(library.correctProgress(actor, { ...request, key: key(), entryId: last.id, expectedVersion: 7, occurredAt: at(6), position: 90 }), fails("INVALID_TRANSITION"));
    await library.correctProgress(actor, { ...request, key: key(), entryId: last.id, expectedVersion: 7, position: 85, occurredAt: at(4) });
    assert.equal((await getHistory()).sessions[0].state, "completed");
    assert.equal((await getHistory()).sessions[0].loggedProgress, 45);
  });
  await t.test("archive remaps correction chains in arbitrary order; clear remains atomic", async () => {
    const archive = JSON.parse(await library.archive(actor));
    assert.equal(archive.version, 4);
    archive.progressEntries.reverse();
    const parsed = parseRowanArchive(JSON.stringify(archive));
    assert.equal(parsed.progressEntries.length, 8);
    const bad = structuredClone(archive);
    const replacement = bad.progressEntries.find((e: { supersedesId: string | null }) => e.supersedesId);
    replacement.supersedesId = replacement.id;
    assert.throws(() => parseRowanArchive(JSON.stringify(bad)), /cyclic|invalid|branched/);
    const orphan = structuredClone(archive);
    orphan.progressEntries.find((e: { supersedesId: string | null }) => e.supersedesId).supersedesId = key();
    assert.throws(() => parseRowanArchive(JSON.stringify(orphan)), /invalid progress correction/);
    const branch = structuredClone(archive);
    const fork = branch.progressEntries.find((e: { supersedesId: string | null }) => e.supersedesId);
    branch.progressEntries.push({ ...fork, id: key() });
    assert.throws(() => parseRowanArchive(JSON.stringify(branch)), /branched/);
    const old = structuredClone(archive);
    old.version = 2;
    old.progressEntries = old.progressEntries.filter((e: { supersedesId: string | null }) => !e.supersedesId);
    for (const e of old.progressEntries) { delete e.supersedesId; delete e.voided; delete e.correctionReason; }
    assert.ok(parseRowanArchive(JSON.stringify(old)).progressEntries.every(e => e.supersedesId === null && !e.voided));
    await accounts.restore(actor, key(), JSON.stringify(archive));
    const restored = JSON.parse(await library.archive(actor));
    assert.equal(restored.progressEntries.length, 8);
    assert.equal(effectiveProgress(restored.progressEntries).length, 3);
    const ids = new Set(restored.progressEntries.map((e: {id: string}) => e.id));
    for (const e of restored.progressEntries) if (e.supersedesId) assert.ok(ids.has(e.supersedesId));
    assert.ok(!ids.has(original.id));
    assert.equal((await library.readingHistory(actor, restored.userBooks[0].id)).sessions[0].loggedProgress, 45);
    assert.deepEqual(await library.listLibrary(other), []);
    await accounts.clear(actor, key());
    assert.deepEqual(await library.listLibrary(actor), []);
  });
  await t.test("paused audio attempts retain units, bounds, and the starting baseline", async () => {
    const audio = await library.saveManual(actor, { key: key(), title: "Audio", author: "Reader", format: "audiobook", total: 3600 });
    const read = await library.startReading(actor, { key: key(), userBookId: audio.userBookId, expectedVersion: 0, startedAt: at(1), unit: "second", position: 120 });
    await library.recordProgress(actor, { key: key(), sessionId: read.sessionId!, expectedVersion: 0, position: 900, occurredAt: at(2) });
    await library.transitionReading(actor, { key: key(), sessionId: read.sessionId!, expectedVersion: 1, action: "pause", occurredAt: at(2) });
    let h = await library.readingHistory(actor, audio.userBookId);
    const observation = h.entries.find(e => e.kind === "observation")!;
    const input = { ...request, key: key(), sessionId: read.sessionId!, entryId: observation.id, expectedVersion: 2, position: 600 };
    await assert.rejects(library.correctProgress(actor, { ...input, position: 3601 }), fails("INVALID_TRANSITION"));
    await assert.rejects(library.correctProgress(actor, { ...input, entryId: h.entries.find(e => e.kind === "baseline")!.id }), fails("INVALID_TRANSITION"));
    await library.correctProgress(actor, input);
    h = await library.readingHistory(actor, audio.userBookId);
    assert.equal(h.sessions[0].state, "paused");
    assert.equal(h.sessions[0].unit, "second");
    assert.equal(h.sessions[0].position, 600);
    assert.equal(h.sessions[0].loggedProgress, 480);
  });

});
