import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useStore, totalReads, lastReadDate } from "@/lib/basgiath-store";
import { BookCover } from "@/components/BookCover";
import { ChevronLeft, Check, Trash2, RotateCcw, CalendarDays, X, Headphones, Pencil } from "lucide-react";
import { useState, useEffect } from "react";

export const Route = createFileRoute("/book/$id")({ component: BookDetail });

function BookDetail() {
  const { id } = Route.useParams();
  const navigate = useNavigate();
  const { books, margins, updateBook, removeBook, finishRead } = useStore();
  const book = books.find((b) => b.id === id);
  const [page, setPage] = useState(""); const [totalPages, setTotalPages] = useState(""); const [minutes, setMinutes] = useState(""); const [totalMins, setTotalMins] = useState("");
  const [showDatePicker, setShowDatePicker] = useState(false); const [finishDate, setFinishDate] = useState(() => new Date().toISOString().split("T")[0]);
  const [editing, setEditing] = useState(false); const [title, setTitle] = useState(""); const [author, setAuthor] = useState(""); const [coverUrl, setCoverUrl] = useState(""); const [tags, setTags] = useState("");

  useEffect(() => { if (book) { setTitle(book.title); setAuthor(book.author); setCoverUrl(book.coverUrl ?? ""); const existingTags = (book.metadata?.tags as string[] | undefined) ?? []; setTags(existingTags.join(", ")); if (book.format === "audiobook") { setMinutes(String(book.currentMinute ?? 0)); setTotalMins(String(book.durationMinutes ?? "")); } else { setPage(String(book.currentPage ?? 0)); setTotalPages(String(book.totalPages ?? "")); } } }, [book]);
  if (!book) return <div className="p-6 text-center"><p className="text-sm text-muted-foreground">Book not found.</p><Link to="/library" className="text-primary text-sm mt-2 inline-block">Back to library</Link></div>;

  const isAudio = book.format === "audiobook"; const myMargins = margins.filter((m) => m.bookId === book.id); const last = lastReadDate(book); const reads = totalReads(book);
  const bookTags = ((book.metadata?.tags as string[] | undefined) ?? []);
  function saveProgress() { if (isAudio) updateBook(book.id, { currentMinute: Math.max(0, Number(minutes) || 0), durationMinutes: totalMins ? Math.max(0, Number(totalMins)) : undefined }); else updateBook(book.id, { currentPage: Math.max(0, Number(page) || 0), totalPages: totalPages ? Math.max(0, Number(totalPages)) : undefined }); }
  function saveBookEdit() { updateBook(book.id, { title: title.trim() || book.title, author: author.trim() || book.author, coverUrl: coverUrl.trim() || null, metadata: { ...(book.metadata ?? {}), tags: tags.split(",").map((t) => t.trim()).filter(Boolean) } }); setEditing(false); }
  const progressPct = isAudio ? (book.durationMinutes ? Math.min(100, Math.round(((book.currentMinute ?? 0) / book.durationMinutes) * 100)) : 0) : (book.totalPages ? Math.min(100, Math.round(((book.currentPage ?? 0) / book.totalPages) * 100)) : 0);

  return <div className="max-w-4xl mx-auto">
    {showDatePicker && <div className="fixed inset-0 z-50 bg-background/80 backdrop-blur-sm flex items-end md:items-center justify-center"><div className="w-full max-w-md bg-card border border-border rounded-md p-5 shadow-xl space-y-4"><div className="flex items-center justify-between"><h2 className="font-display text-lg">When did you finish?</h2><button onClick={() => setShowDatePicker(false)}><X className="h-5 w-5" /></button></div><label className="text-xs text-muted-foreground flex items-center gap-1.5"><CalendarDays className="h-3.5 w-3.5" /> Finished date</label><input type="date" value={finishDate} onChange={(e) => setFinishDate(e.target.value)} max={new Date().toISOString().split("T")[0]} className="w-full bg-muted rounded-md px-3 py-2 text-sm outline-none"/><div className="flex gap-2"><button onClick={() => setShowDatePicker(false)} className="flex-1 text-sm py-2.5 rounded-md border border-border">Cancel</button><button onClick={() => { finishRead(book.id, new Date(finishDate + "T12:00:00").toISOString()); setShowDatePicker(false); }} className="flex-1 bg-primary text-primary-foreground rounded-md py-2.5 text-sm font-medium"><Check className="h-4 w-4 inline" /> Confirm</button></div></div></div>}
    <div className="px-5 md:px-8 pt-4 pb-2 flex items-center justify-between"><button onClick={() => navigate({ to: "/library" })} className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground"><ChevronLeft className="h-5 w-5" /> Back</button><div className="flex gap-2"><button onClick={() => setEditing((v) => !v)} className="text-muted-foreground/70 hover:text-foreground p-1"><Pencil className="h-4 w-4" /></button><button onClick={() => { if (confirm("Remove this book and all its margins?")) { removeBook(book.id); navigate({ to: "/library" }); } }} className="text-muted-foreground/70 hover:text-destructive p-1"><Trash2 className="h-4 w-4" /></button></div></div>
    <div className="px-5 md:px-8 grid md:grid-cols-[180px,1fr] gap-4 items-start"><BookCover book={book} size="lg" /><div><h1 className="font-display text-2xl">{book.title}</h1><p className="text-sm text-muted-foreground mt-1">{book.author}</p>{isAudio && <span className="inline-flex items-center gap-1 mt-2 text-[11px] bg-primary/10 text-primary rounded-full px-2 py-0.5"><Headphones className="h-3 w-3" /> Audiobook</span>}<p className="text-[11px] text-muted-foreground/80 mt-2">{reads === 0 ? "Not yet finished" : `Read ${reads} time${reads > 1 ? "s" : ""}${last ? ` · last ${new Date(last).toLocaleDateString()}` : ""}`}</p><div className="flex flex-wrap gap-1 mt-2">{bookTags.map((tag)=><span key={tag} className="text-[11px] px-2 py-0.5 bg-muted rounded-md">{tag}</span>)}</div></div></div>
    {editing && <section className="px-5 md:px-8 mt-4"><div className="bg-card border border-border rounded-md p-4 space-y-2"><h2 className="font-display text-lg">Edit book details</h2><input value={title} onChange={(e)=>setTitle(e.target.value)} className="w-full bg-muted rounded-md px-3 py-2 text-sm" placeholder="Title"/><input value={author} onChange={(e)=>setAuthor(e.target.value)} className="w-full bg-muted rounded-md px-3 py-2 text-sm" placeholder="Author"/><input value={coverUrl} onChange={(e)=>setCoverUrl(e.target.value)} className="w-full bg-muted rounded-md px-3 py-2 text-sm" placeholder="Cover image URL"/><input value={tags} onChange={(e)=>setTags(e.target.value)} className="w-full bg-muted rounded-md px-3 py-2 text-sm" placeholder="Genre tags, comma separated"/><button onClick={saveBookEdit} className="w-full bg-primary text-primary-foreground py-2 rounded-md text-sm">Save book changes</button></div></section>}

    <section className="px-5 md:px-8 mt-6"><div className="bg-card border border-border rounded-md p-4">
      <h2 className="font-display text-lg mb-2">{isAudio ? "Progress" : "Bookmark"}</h2>
      {isAudio ? <div className="grid grid-cols-3 gap-2"><input value={minutes} onChange={(e)=>setMinutes(e.target.value.replace(/\D/g,""))} className="bg-muted rounded-md px-3 py-2 text-sm" placeholder="Current (min)"/><input value={totalMins} onChange={(e)=>setTotalMins(e.target.value.replace(/\D/g,""))} className="bg-muted rounded-md px-3 py-2 text-sm" placeholder="Total (min)"/><button onClick={saveProgress} className="bg-primary text-primary-foreground rounded-md text-sm">Save</button></div> : <div className="grid grid-cols-3 gap-2"><input value={page} onChange={(e)=>setPage(e.target.value.replace(/\D/g,""))} className="bg-muted rounded-md px-3 py-2 text-sm" placeholder="Current page"/><input value={totalPages} onChange={(e)=>setTotalPages(e.target.value.replace(/\D/g,""))} className="bg-muted rounded-md px-3 py-2 text-sm" placeholder="Total pages"/><button onClick={saveProgress} className="bg-primary text-primary-foreground rounded-md text-sm">Save</button></div>}
      <p className="text-[11px] text-muted-foreground mt-2">{progressPct}% complete</p>
      <button onClick={() => setShowDatePicker(true)} className="mt-2 w-full inline-flex items-center justify-center gap-1 bg-gold text-gold-foreground rounded-md py-2 text-sm font-medium"><Check className="h-4 w-4" /> Mark finished</button>
    </div></section>
    <section className="px-5 md:px-8 mt-6 mb-8"><h2 className="font-display text-lg mb-2">Margins</h2>{myMargins.length===0?<p className="text-sm text-muted-foreground">No notes yet for this book.</p>:<ul className="space-y-2">{myMargins.map((m)=><li key={m.id} className="bg-card border border-border rounded-md p-3"><p className="text-sm">{m.text}</p>{m.page && <p className="text-xs text-muted-foreground mt-1">p. {m.page}</p>}</li>)}</ul>}</section>
  </div>;
}
