/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MarginsRouteImport } from './routes/margins'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarginIdRouteImport } from './routes/margin.$id'
import { Route as BookIdRouteImport } from './routes/book.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MarginsRoute = MarginsRouteImport.update({
  id: '/margins',
  path: '/margins',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarginIdRoute = MarginIdRouteImport.update({
  id: '/margin/$id',
  path: '/margin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/goals': typeof GoalsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/margins': typeof MarginsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/book/$id': typeof BookIdRoute
  '/margin/$id': typeof MarginIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/goals': typeof GoalsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/margins': typeof MarginsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/book/$id': typeof BookIdRoute
  '/margin/$id': typeof MarginIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/goals': typeof GoalsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/margins': typeof MarginsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/book/$id': typeof BookIdRoute
  '/margin/$id': typeof MarginIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/goals'
    | '/library'
    | '/login'
    | '/margins'
    | '/profile'
    | '/settings'
    | '/book/$id'
    | '/margin/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/goals'
    | '/library'
    | '/login'
    | '/margins'
    | '/profile'
    | '/settings'
    | '/book/$id'
    | '/margin/$id'
  id:
    | '__root__'
    | '/'
    | '/goals'
    | '/library'
    | '/login'
    | '/margins'
    | '/profile'
    | '/settings'
    | '/book/$id'
    | '/margin/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GoalsRoute: typeof GoalsRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  MarginsRoute: typeof MarginsRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  BookIdRoute: typeof BookIdRoute
  MarginIdRoute: typeof MarginIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/margins': {
      id: '/margins'
      path: '/margins'
      fullPath: '/margins'
      preLoaderRoute: typeof MarginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/margin/$id': {
      id: '/margin/$id'
      path: '/margin/$id'
      fullPath: '/margin/$id'
      preLoaderRoute: typeof MarginIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GoalsRoute: GoalsRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  MarginsRoute: MarginsRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  BookIdRoute: BookIdRoute,
  MarginIdRoute: MarginIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
